name: Dismiss Stale Approvals

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]

jobs:
  dismiss_stale_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Dismiss stale approvals
        uses: hmarr/dismiss-stale-approvals@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
